###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Leider Monrantes",
    "document": "987654",
    "email": "leider@correo.com",
    "password": "987654"
}

###
POST http://localhost:9000/login/credencial HTTP/1.1
Content-Type: application/json

{
    "email": "leider@correo.com",
    "password": "987654"
}